//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExcelMapping
    {
        public string ExcelName { get; set; }
        public string ColumnName { get; set; }
        public string FieldName { get; set; }
        public string DefaultValue { get; set; }
        public string DataType { get; set; }
        public string SheetName { get; set; }
        public int X { get; set; }
        public string NewLineChar { get; set; }
    
        public virtual tblExcelSetting tblExcelSetting { get; set; }
    }
}
