//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblXMLMapping
    {
        public string XMLName { get; set; }
        public string TagName { get; set; }
        public string FieldName { get; set; }
        public string DefaultValue { get; set; }
        public string FatherTag { get; set; }
        public bool CanRepeat { get; set; }
        public int Idx { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Updator { get; set; }
    
        public virtual tblXMLSetting tblXMLSetting { get; set; }
    }
}
